// <copyright file="CarFactory.cs" company="HI1">
//     Copyright ©  2016
// </copyright>
// <summary>CarFactory</summary>
// ***********************************************************************

namespace Visualizer.Factories
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Visualizer.Utilities;
    using Visualizer.ViewModels;
    using Visualizer.Views;

    /// <summary>
    /// CarFactory Class
    /// </summary>
    /// <autogeneratedoc />
    public class CarFactory
    {
        #region Methods

        /// <summary>
        /// Creates the character.
        /// </summary>
        /// <param name="x">The x.</param>
        /// <param name="y">The y.</param>
        /// <param name="r">The r.</param>
        /// <param name="main">The main.</param>
        /// <param name="id">The identifier.</param>
        /// <param name="type">The type.</param>
        /// <returns>
        /// the CharacterViewModel
        /// </returns>
        public EmergencyCarViewModel CreateCar(int x, int y, int r, MainWindow main, int id, int type)
        {
            EmergencyCarViewModel car = null;
            switch (type)
            {
                case 1:
                    car = new NormalCarViewModel(new VRPosition(x, y, r), id);
                    break;
                case 2:
                    car = new PoliceCarViewModel(new VRPosition(x, y, r), id);
                    break;
                case 3:
                    car = new AmbulanceCarViewModel(new VRPosition(x, y, r), id);
                    break;
                case 4:
                    car = new FiretruckCarViewModel(new VRPosition(x, y, r), id);
                    break;
            }
            
            CarView view = new CarView();
            view.DataContext = car;
            main.AddControl(view);
            return car;
        }

        #endregion Methods
    }
}
