// <copyright file="AbstractCarModel.cs" company="HI1">
//     Copyright ©  2016
// </copyright>
// <summary>AbstractCarModel class</summary>
// ***********************************************************************

namespace Visualizer.Models.Cars
{
    using System.Windows.Media.Imaging;
    using Utilities;

    /// <summary>
    /// Class EmergencyCarModel.
    /// </summary>
    /// <seealso cref="Visualizer.Models.Cars.CarModel" />
    public abstract class AbstractCarModel : AbstractVRObject
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="AbstractCarModel" /> class.
        /// </summary>
        /// <param name="pos">The position.</param>
        /// <param name="id">The identifier.</param>
        /// <autogeneratedoc />
        public AbstractCarModel(VRPosition pos, int id)
            : base(pos, id)
        {
            this.IconImage = ImageMap.GetImage(ImageEnum.CarIcon.ToString());
            this.SirenOn = false;
            this.Width = 75;
            this.Height = 150;
        }

        #endregion Constructors

        #region Properties

        /// <summary>
        /// Gets or sets the width
        /// </summary>
        /// <autogeneratedoc />
        public int Width { get; set; }

        /// <summary>
        /// Gets or sets the height
        /// </summary>
        /// <autogeneratedoc />
        public int Height { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [siren on].
        /// </summary>
        /// <value><c>true</c> if [siren on]; otherwise, <c>false</c>.</value>
        public bool SirenOn { get; set; }

        /// <summary>
        /// Gets or sets the icon image.
        /// </summary>
        /// <value>The position.</value>
        public BitmapImage IconImage { get; protected set; }

        /// <summary>
        /// Gets or sets the main image.
        /// </summary>
        /// <value>The position.</value>
        public BitmapImage Image { get; protected set; }

        #endregion Properties
    }
}