// <copyright file="AmbulanceCarModel.cs" company="HI1">
//     Copyright ©  2016
// </copyright>
// <summary>AmbulanceCar class</summary>
// ***********************************************************************

namespace Visualizer.Models.Cars
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Visualizer.Utilities;

    /// <summary>
    /// Model for an ambulance car
    /// </summary>
    /// <seealso cref="Visualizer.Models.Cars.AmbulanceCarModel" />
    /// <autogeneratedoc />
    public class AmbulanceCarModel : AbstractCarModel
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="AmbulanceCarModel"/> class.
        /// </summary>
        /// <param name="pos">The position.</param>
        /// <param name="id">The identifier.</param>
        public AmbulanceCarModel(VRPosition pos, int id)
            : base(pos, id)
        {
            this.Image = ImageMap.GetImage(ImageEnum.AmbulanceCar.ToString());
        }

        #endregion Constructors
    }
}