// <copyright file="FiretruckCarModel.cs" company="HI1">
//     Copyright ©  2016
// </copyright>
// <summary>FiretruckCar class</summary>
// ***********************************************************************

namespace Visualizer.Models.Cars
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Visualizer.Utilities;

    /// <summary>
    /// Model for a fire truck car
    /// </summary>
    /// <seealso cref="Visualizer.Models.Cars.AbstractEmergencyCarModel" />
    /// <autogeneratedoc />
    public class FiretruckCarModel : AbstractCarModel
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="FiretruckCarModel"/> class.
        /// </summary>
        /// <param name="pos">The position.</param>
        /// <param name="id">The identifier.</param>
        public FiretruckCarModel(VRPosition pos, int id)
            : base(pos, id)
        {
            this.Image = ImageMap.GetImage(ImageEnum.FireFighterCar.ToString());
            this.Height = 300;
        }

        #endregion Constructors
    }
}