// <copyright file="PoliceCarViewModel.cs" company="HI1">
//     Copyright ©  2016
// </copyright>
// <summary>PoliceCarViewModel class</summary>
// ***********************************************************************

namespace Visualizer.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Windows.Media;
    using Visualizer.Models.Cars;
    using Visualizer.Utilities;

    /// <summary>
    /// PoliceCarViewModel Class
    /// </summary>
    /// <seealso cref="Visualizer.ViewModels.EmergencyCarViewModel" />
    /// <autogeneratedoc />
    public class PoliceCarViewModel : EmergencyCarViewModel
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="PoliceCarViewModel"/> class.
        /// </summary>
        /// <param name="pos">The position.</param>
        /// <param name="id">The identifier.</param>
        public PoliceCarViewModel(VRPosition pos, int id)
            : base(pos, id)
        {
            this.CarModel = new PoliceCarModel(pos, id);
            this.CarImage = new ImageBrush();
            this.GetCarImage();
            this.CarIconImage = new ImageBrush();
            this.GetCarIconImage();
            this.Model = this.CarModel;
            this.Height = this.CarModel.Height;
            this.Width = this.CarModel.Width;
            this.SetPosition(pos);
        }

        #endregion Constructors
    }
}
